version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.3
jobs:
  build:
    docker:
      - image: cimg/node:18.9.1
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Deploy to Elastic-Beanstalk
          no_output_timeout: 30m
          command: |
            npm run deploy
